import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Button, Card, CardHeader } from "@/components/ui"
import Link from "next/link"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Card className="mb-8">
          <CardHeader className="flex flex-row gap-x-4 space-y-0">
            <Button variant="outline" asChild>
              <Link href="/examples/ssr">SSR Examples Page</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/examples/csr">CSR Examples Page</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/examples/ssg">SSG Examples Page</Link>
            </Button>
          </CardHeader>
        </Card>
        {children}
      </body>
    </html>
  )
}
